### ISSUE TITLE
Chatbot Setup Checklist 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/BrowTricks#3]
We use chatbots in our sites for setting up subscriber accounts and client booking, screenshot below is an example of the "book appointment" chatbot 
![Book Appointment](https://user-images.githubusercontent.com/5694308/76829052-dfd45e80-6854-11ea-93d7-d5069adc69cf.jpg)

We will be using Twilio for our chatbots 

### Components
This is the setup checklist for all chatbot components
- [ ] Chat Card #4 - These are the simple text interactions on the chatbot 
![Group 33](https://user-images.githubusercontent.com/5694308/76827580-bebe3e80-6851-11ea-91bd-adcfa56157a9.png)
![Group 49](https://user-images.githubusercontent.com/5694308/76828125-d6e28d80-6852-11ea-86a8-12c9d20d6761.png)

- [ ] Selection Card #5 - These cards let users select from a list of options
![Selection Module Chatbot](https://user-images.githubusercontent.com/5694308/76825729-46ee1500-684d-11ea-94c6-e351d0627231.png)

- [ ] Service Display Card #7  - This card shows user service details and prompts them to book the services. 
![Service Display Card](https://user-images.githubusercontent.com/5694308/76825792-6edd7880-684d-11ea-81ee-6ab4b6a35400.png)

- [ ] Date/Time Selection Card #9 - These card let you select date, then switches to let you select time
![Group 37](https://user-images.githubusercontent.com/5694308/76825840-90d6fb00-684d-11ea-87cf-c2dde829ec74.png)
![Frame 109](https://user-images.githubusercontent.com/5694308/76825844-92082800-684d-11ea-9325-e1fab8ef1041.png)

- [ ] Text Input Card - #8 These cards include text input fields and buttons to submit info 
![image](https://user-images.githubusercontent.com/5694308/77278345-bbafcc00-6cf1-11ea-8378-00986b7e9e28.png)

### Design File 
https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179
This is the design file for Brow Tricks. The "Prototype" page contains all the screens necessary for the app

**Comment by mort3za** [comment]
3 days for UI, But about integrating with Twilio can't say now, should have a deep look at it, probably the bigger part of this task is managing store and connecting to Twilio properly.
@atharva3010 Do you have any idea?

**Comment by atharva3010** [comment]
@mort3za Twilio works best for SMS and IVR chatbots, work building our own app in a chat like manner, we should do it via our own api. If you want to build SMS flows, then you can use twilio. Building an SMS flow using twilio is very easy, takes only a couple of hours for even very complex flows. Deployment is managed by twilio too. @paulchrisluke can add you to our twilio team, you can whitelist your number (using a fake US based no. is advisable for testing) then you can send an SMS to our twilio number and try out the flow. I have managed error handling and everything. It supports adding widgets in the flow which can make api requests, can run node.js functions, etc.
